### PR TITLE
Fix #1 --- infinite loop in text.Wrap

### LINKED ISSUE #1: Infinite loop in text.Wrap() if input is lacking spaces
When calling text.Wrap(), if the input string:
1. has no spaces, and
2. is longer than the wrap size, 
then the function will loop forever and consume all available memory.

Sample program (be careful running this, it will consume all available memory):

```
package main

import (
    "github.com/kr/text"
)

func main() {
    text.Wrap("aaaaa", 4)
}
```

### PR DESCRIPTION
**Pull request by BurntSushi**
I'm hoping that this fixes #1.

I don't completely grok the algorithm yet, so I'm not sure if I've broken anything. But the tests pass.

### CODE REVIEW

**Comment by rubenv** [comment]
@kr Any chance to get this merged?

**Comment by rubenv** [comment]
No, never mind, this doesn't work. I'm still getting the infinite loop.

**Comment by BurntSushi** [comment]
@rubenv On the same test case as in #1?

@kr - Perhaps you could lend some insight here?

**Comment by rubenv** [comment]
I've worked around this by using the ToText method from the std lib: http://godoc.org/go/doc#ToText

**Pull request closed without merging**
