### PR TITLE
Wrap unicode text correctly

### PR DESCRIPTION
**Pull request by ghost**
This pull request fixes text wrapping for codepoints above U+007F. It's not perfect, because neither is `go-runewidth`, but it is very, very close.

### CODE REVIEW

**Comment by kr** [comment]
Currently, the package documentation says that it treats each byte as one unit. That might not be particularly useful, but the current behavior is at least correct according to the package doc.

Could you define what behavior you're looking for? You say that this patch is "not perfect", but what _would_ be perfect, exactly?

**Comment by ghost** [comment]
Oh, right, I hadn't noticed the documentation. You're right, the current behaviour is correctly documented; it's just a matter of whether it's deemed useful or not. I'll append a patch for the documentation so that you can see what it would look like.

By "not perfect" I mean that `go-runewidth` gets confused with certain edge cases, such as grapheme clusters with zero-width joiners used on some emojis. A perfect patch would calculate the width of complex grapheme clusters correctly.

**Comment by ghost** [comment]
Done.

Personally, I think this library is about presentation of text in column-wrapped context; as such, it needs to be able to tell what a character looks like and how much space it takes. Even if that was considered out of scope for the library, considering multi-byte UTF-8 codepoints as more than one character would almost surely be in scope.

For comparison, this is what wrapped Chinese text on my terminal drawing library, [`dit`](https://github.com/slapresta/dit), looks like with this patch:

screen shot 2016-01-30 at 11 12 53

And this is what it looked like before:

screen shot 2016-01-30 at 11 12 40

As you can see, the width of Chinese characters is being overestimated (by considering each Chinese character as three or four units), but, if multi-byte UTF-8 codepoints were considered to have width one regardless of their content, it would be greatly underestimated, since each Chinese character uses two cells. It would also overestimate characters using combining diacritics.

**Comment by kr** [comment]
It seems like golang.org/x/text/unicode/norm might also potentially be useful here. In addition, to make sure the visual display looks less ragged, we should really take into account font metrics. I started with just one unit per byte because that was easy to get going.

But now that it's time to do something more, I'd rather go as far as possible without needing to drastically change the algorithm. (Full unicode text shaping is [very complicated](http://harfbuzz.org/).) Taking one or two callback functions would letting the user use any units they like for word width and space width, without introducing a hard dependency on any particular measurement package. It would be a pretty straightforward change, along the lines of this patch, but would probably also need to define a configuration type to hold the measurement functions.

How does that sound?

**Comment by ghost** [comment]
That sounds great for a long-term vision, but I'm not sure if adding that _now_ would pay off. It's definitely the way to go whenever you want the library to take into account font metrics and the like, but I would be wary of introducing so much complexity now.

Right now, the simple patch provided by this pull request gets noticeably closer to the end goal, way ahead of assuming one unit per byte. Perhaps you could open an issue with your comment as contents, so that it is taken into account when dynamic font measurements are considered.

**Comment by kr** [comment]
I'm not suggesting introducing significantly more complexity than this patch already does, just making a callback function to measure the width of text, and providing some sensible defaults. I opened #5 to illustrate.

I hesitate to make go-runewidth the only available behavior, because that package makes some assumptions about how runes will be displayed. It works out well for your particular case, but it won't work out well for everyone. (Of course, the existing behavior also makes assumptions about display. If we're taking the trouble to change it, I'd like to remove those assumptions and make the behavior better, not just different.)

Using #5, you can use runewidth.StringWidth as the text measurement function if you want.

**Comment by ghost** [comment]
Alright, that makes sense to me. We can close this one and merge #5 instead.

**Comment by ghost** [comment]
I closed this one since #5 seems to be the way to go. Thanks! :)

**Pull request closed without merging**
